/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.eni.dvtejb.metier.sessions {

    [Bindable]
    [RemoteClass(alias="com.eni.dvtejb.metier.sessions.FacadeBean")]
    public class FacadeBean extends FacadeBeanBase {

        override public function get nombreTotalArticles():int {
            // TODO: Gas3 default generated getter.
            return 0;
        }
    }
}