/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.eni.dvtejb.metier.sessions {

    import org.granite.collections.IMap;

    [Bindable]
    [RemoteClass(alias="com.eni.dvtejb.metier.sessions.PanierCycleBean")]
    public class PanierCycleBean extends PanierCycleBeanBase {

        override public function get contenuPanier():IMap {
            // TODO: Gas3 default generated getter.
            return null;
        }
    }
}