/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.eni.dvtejb.metier.sessions {

    import mx.collections.ListCollectionView;

    [Bindable]
    [RemoteClass(alias="com.eni.dvtejb.metier.sessions.PanierBean")]
    public class PanierBean extends PanierBeanBase {

        override public function get montantTotal():Number {
            // TODO: Gas3 default generated getter.
            return Number.NaN;
        }

        override public function get panier():ListCollectionView {
            // TODO: Gas3 default generated getter.
            return null;
        }

        override public function get produits():ListCollectionView {
            // TODO: Gas3 default generated getter.
            return null;
        }
    }
}