/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.eni.dvtejb.metier.entities {

    [Bindable]
    [RemoteClass(alias="com.eni.dvtejb.metier.entities.Gestionnaire")]
    public class Gestionnaire extends GestionnaireBase {
    }
}